Consumables = {

	midori 						= { emote = "beer3", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 10, 20 }, canOD = true }},
	prosecco 					= { emote = "beer3", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 10, 20 }, canOD = true }},
	tequila 					= { emote = "beer3", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 10, 20 }, canOD = true }},
	triplsec 					= { emote = "beer3", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 10, 20 }, canOD = true }},
	gin 						= { emote = "ginb", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 10, 20 }, canOD = true }},
	rum 						= { emote = "rumb", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 10, 20 }, canOD = true }},
	amaretto 					= { emote = "whiskey", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 10, 20 }, canOD = true }},
	amarettosour 				= { emote = "whiskey", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 40, 50 }, canOD = true }},
	bellini 					= { emote = "whiskey", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 40, 50 }, canOD = true }},
	cosmopolitan 				= { emote = "whiskey", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 40, 50 }, canOD = true }},
	longisland 					= { emote = "whiskey", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 40, 50 }, canOD = true }},
	margarita 					= { emote = "whiskey", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 40, 50 }, canOD = true }},
	pinacolada 					= { emote = "whiskey", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 40, 50 }, canOD = true }},
	sangria 					= { emote = "whiskey", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 40, 50 }, canOD = true }},
	screwdriver 				= { emote = "whiskey", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 40, 50 }, canOD = true }},
	strawdaquiri 				= { emote = "whiskey", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 40, 50 }, canOD = true }},
	strawmargarita 				= { emote = "whiskey", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 40, 50 }, canOD = true }},
	ambeer 						= { emote = "beer3", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 10, 20 }, canOD = true }},
	dusche 						= { emote = "beer1", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 10, 20 }, canOD = true }},
	logger 						= { emote = "beer2", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 10, 20 }, canOD = true }},
	pisswasser 					= { emote = "beer4", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 10, 20 }, canOD = true }},
	pisswasser2 				= { emote = "beer5", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 10, 20 }, canOD = true }},
	pisswasser3 				= { emote = "beer6", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "alcohol", stats = { thirst = { 10, 20 }, canOD = true }},
	cranberry 					= { emote = "wine", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "drink", stats = { thirst = { 20, 20 }, }},
	pinejuice 					= { emote = "wine", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "drink", stats = { thirst = { 40, 50 }, }},
	ecola						= { emote = "ecola", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "drink", stats = { thirst = { 10, 20 }, }},
	ecolalight 					= { emote = "ecola", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "drink", stats = { thirst = { 10, 20 }, }},
	sprunk 						= { emote = "sprunk", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "drink", stats = { thirst = { 10, 20 }, }},
	sprunklight 				= { emote = "sprunk", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "drink", stats = { thirst = { 10, 20 }, }},
	crisps 						= { emote = "crisps", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "food", stats = { hunger = { 20, 30 }, }},
	cubasil 					= { emote = "burger", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "food", stats = { hunger = { 20, 30 }, }},
	mintleaf 					= { emote = "burger", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "food", stats = { hunger = { 20, 30 }, }},
	peach 						= { emote = "burger", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "food", stats = { hunger = { 20, 30 }, }},
	strawberry 					= { emote = "burger", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "food", stats = { hunger = { 20, 30 }, }},
	chocolate 					= { emote = "egobar", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "food", stats = { hunger = { 20, 30 }, }},
	nplate 						= { emote = "burger", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "food", stats = { hunger = { 40, 50 }, }},
	vusliders 					= { emote = "burger", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "food", stats = { hunger = { 40, 50 }, }},
	vutacos 					= { emote = "burger", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "food", stats = { hunger = { 40, 50 }, }},
	tots 						= { emote = "burger", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "food", stats = { hunger = { 40, 50 }, }},
	nachos 						= { emote = "burger", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "food", stats = { hunger = { 40, 50 }, }},
    coffee 						= { emote = "coffee", 		canRun = false, time = { 5000, 6000 }, stress = 0, heal = 0, armor = 0, type = "drink", stats = { time = 10000, thirst = { 10,15 }, }},

	sprunk_glass				= { emote = "glass", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "drink", stats = { thirst = { 10, 20 }, }},
	sprunklight_glass			= { emote = "glass", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "drink", stats = { thirst = { 10, 20 }, }},
	ecola_glass					= { emote = "glass", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "drink", stats = { thirst = { 10, 20 }, }},
	ecolalight_glass			= { emote = "glass", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "drink", stats = { thirst = { 10, 20 }, }},
	raine_glass					= { emote = "glass", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "drink", stats = { thirst = { 10, 20 }, }},
	junkdrink_glass				= { emote = "glass", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "drink", stats = { thirst = { 10, 20 }, }},
	orangotang_glass			= { emote = "glass", 		canRun = true, time = { 5000, 6000 }, stress = { 2, 4 }, heal = 0, armor = 0, type = "drink", stats = { thirst = { 10, 20 }, }},


}