Crafting = Crafting or {}

Crafting.bahamaCocktails = {
    Header = locale("menu", "cocktail"),
    Anims = CraftingEmotes.Shake,
    progressBar = {
        label = locale("progressbar", "progress_mix"),
        time = 4000,
    },
    Recipes = {
        { amarettosour = { amaretto = 1, lemon = 1, },
            ["amount"] = 1,
        },
        { bellini = { prosecco = 1, peach = 1, },
            ["amount"] = 1,
        },
        { cosmopolitan = { vodka = 1, orange = 1,	cranberry = 1, cubasil = 1, },
            ["amount"] = 1,
        },
        { longisland = { gin = 1, tequila = 1, vodka = 1, ecola = 1, lemon = 1, },
            ["amount"] = 1,
        },
        { margarita = { tequila = 1, lime = 1, orange = 1, },
            ["amount"] = 1,
        },
        { pinacolada = { rum = 1, pinejuice = 1, },
            ["amount"] = 1,
        },
        { sangria = { prosecco = 1, sprunk = 1, orange = 1, mintleaf = 1, },
            ["amount"] = 1,
        },
        { screwdriver = { vodka = 1, orange = 1, },
            ["amount"] = 1,
        },
        { strawdaquiri = { rum = 1, strawberry = 1, },
            ["amount"] = 1,
        },
        { strawmargarita = { tequila = 1, strawberry = 1, },
            ["amount"] = 1,
        },
    },
}

Crafting.bahamaFood = {
    Header = locale("menu", "oven"),
    Anims = CraftingEmotes.Oven,
    progressBar = {
        label = locale("progressbar", "progress_make"),
        time = 7000,
    },
    Recipes = {
        { vusliders = { meat = 1, lettuce = 1, },
            ["amount"] = 1,
        },
        { vutacos = { meat = 1, lettuce = 1, },
            ["amount"] = 1,
        },
        { nplate = { nachos = 1, cheddar = 1, },
            ["amount"] = 1,
        },
        { tots = { potato = 1, },
            ["amount"] = 1,
        },
    },
}

Crafting.bahamaBeer = {
    Header = locale("menu", "beer"),
    Anims = CraftingEmotes.Pour,
    progressBar = {
        label = locale("progressbar", "progress_pour"),
        time = 4000,
    },
    Recipes = {
        { ambeer = {  },
            ["amount"] = 1,
        },
        { dusche = {  },
            ["amount"] = 1,
        },
        { logger = {  },
            ["amount"] = 1,
        },
        { pisswasser = {  },
            ["amount"] = 1,
        },
        { pisswasser2 = {  },
            ["amount"] = 1,
        },
        { pisswasser3 = {  },
            ["amount"] = 1,
        },
    },
}