["boostingtab"] = {
    name = "boostingtab",
    label = "Boosting Tablet",
    weight = 800.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'boostingtab.png',
},
["lockpick"] = {
    name = "lockpick",
    label = "Lockpick",
    weight = 100.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'lockpick.png',
},
["hackingtab"] = {
    name = "hackingtab",
    label = "Hacking Tablet",
    weight = 800.0,
    useable = false,
    shouldClose = true,
    type = 'item',
    image = 'hackingtab.png',
},

["xenonsbleu"] = {
    name = "xenonsbleu",
    label = "Blue Xenons",
    weight = 100.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'xenonsbleu.png',
},
["xenonsbleuelect"] = {
    name = "xenonsbleuelect",
    label = "Electric Blue Xenons",
    weight = 100.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'xenonsbleuelect.png',
},
["xenonsmenthe"] = {
    name = "xenonsmenthe",
    label = "Mint Xenons",
    weight = 100.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'xenonsmenthe.png',
},
["xenonsvert"] = {
    name = "xenonsvert",
    label = "Green Xenons",
    weight = 100.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'xenonsvert.png',
},
["xenonsjaune"] = {
    name = "xenonsjaune",
    label = "Yellow Xenons",
    weight = 100.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'xenonsjaune.png',
},
["xenonsgold"] = {
    name = "xenonsgold",
    label = "Gold Xenons",
    weight = 100.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'xenonsgold.png',
},
["xenonsorange"] = {
    name = "xenonsorange",
    label = "Orange Xenons",
    weight = 100.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'xenonsorange.png',
},
["xenonsrouge"] = {
    name = "xenonsrouge",
    label = "Red Xenons",
    weight = 100.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'xenonsrouge.png',
},
["xenonsrose"] = {
    name = "xenonsrose",
    label = "Pink Xenons",
    weight = 100.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'xenonsrose.png',
},
["xenonsrose2"] = {
    name = "xenonsrose2",
    label = "Hot Pink Xenons",
    weight = 100.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'xenonsrose2.png',
},
["xenonsmauve"] = {
    name = "xenonsmauve",
    label = "Purple Xenone",
    weight = 100.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'xenonsmauve.png',
},
["xenonsblacklight"] = {
    name = "xenonsblacklight",
    label = "Blacklight Xenons",
    weight = 100.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'xenonsblacklight.png',
},
["xenonsdefault"] = {
    name = "xenonsdefault",
    label = "White Xenons",
    weight = 100.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'xenonsdefault.png',
},
["turbo"] = {
    name = "turbo",
    label = "Turbo Kit",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'turbo.png',
},
["engine1"] = {
    name = "engine1",
    label = "Engine Lvl. 1",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'engine1.png',
},
["engine2"] = {
    name = "engine2",
    label = "Engine Lvl. 2",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'engine2.png',
},
["engine3"] = {
    name = "engine3",
    label = "Engine Lvl. 3",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'engine3.png',
},
["engine4"] = {
    name = "engine4",
    label = "Engine Lvl. 4",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'engine4.png',
},
["brakes1"] = {
    name = "brakes1",
    label = "Brakes Lvl. 1",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'brakes1.png',
},
["brakes2"] = {
    name = "brakes2",
    label = "Brakes Lvl. 2",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'brakes2.png',
},
["brakes3"] = {
    name = "brakes3",
    label = "Brakes Lvl. 3",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'brakes3.png',
},
["trans1"] = {
    name = "trans1",
    label = "Transmission Lvl. 1",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'trans1.png',
},
["trans2"] = {
    name = "trans2",
    label = "Transmission Lvl. 2",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'trans2.png',
},
["trans3"] = {
    name = "trans3",
    label = "Transmission Lvl. 3",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'trans3.png',
},
["susp1"] = {
    name = "susp1",
    label = "Suspension Lvl. 1",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'susp1.png',
},
["susp2"] = {
    name = "susp2",
    label = "Suspension Lvl. 2",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'susp2.png',
},
["susp3"] = {
    name = "susp3",
    label = "Suspension Lvl. 3",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'susp3.png',
},
["susp4"] = {
    name = "susp4",
    label = "Suspension Lvl. 4",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'susp4.png',
},
["arm1"] = {
    name = "arm1",
    label = "Armor Lvl. 1",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'arm1.png',
},
["arm2"] = {
    name = "arm2",
    label = "Armor Lvl. 2",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'arm2.png',
},
["arm3"] = {
    name = "arm3",
    label = "Armor Lvl. 3",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'arm3.png',
},
["arm4"] = {
    name = "arm4",
    label = "Armor Lvl. 4",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'arm4.png',
},
["arm5"] = {
    name = "arm5",
    label = "Armor Lvl. 5",
    weight = 1000.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'arm5.png',
},
["win1"] = {
    name = "win1",
    label = "Light Smoke Window Tint",
    weight = 100.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'win1.png',
},
["win2"] = {
    name = "win2",
    label = "Dark Smoke Window Tint",
    weight = 100.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'win2.png',
},
["win3"] = {
    name = "win3",
    label = "Limo Window Tint",
    weight = 100.0,
    useable = true,
    shouldClose = true,
    type = 'item',
    image = 'win3.png',
},
