Config.LabProps = {
    {
        Label = 'Tables',
        Items = {
            { model = 'v_ret_ml_tablea',          name = 'Table A' },
            { model = 'v_ret_ml_tableb',          name = 'Table B' },
            { model = 'v_ret_ml_tablec',          name = 'Table C' },
            { model = 'bkr_prop_weed_table_01a',  name = 'Weed Table' },
            { model = 'bkr_prop_coke_table01a',   name = 'Coke Table' },
            { model = 'bkr_prop_meth_table01a',   name = 'Meth Table' },
            { model = 'bkr_prop_meth_bigbag_02a', name = 'Meth Bigbag' },
            { model = 'prop_table_03b',           name = 'Lab Work Table' },
        },
    },
    {
        Label = 'Lighting',
        Items = {
            { model = 'xm_prop_lab_wall_lampa',            name = 'Wall Lampa' },
            { model = 'xm_prop_x17_sub_lampa_small_yel',   name = 'Lamp Small Yellow' },
            { model = 'xm_prop_x17_sub_lampa_large_white', name = 'Lamp Large White' },
            { model = 'prop_worklight_03a',                name = 'Work Light' },
        },
    },
    {
        Label = 'Money Wash',
        Items = {
            { model = 'bkr_prop_money_counter',     name = 'Money Counter' },
            { model = 'bkr_prop_money_pokerbucket', name = 'Poker Bucket' },
            { model = 'bkr_prop_money_sorted_01',   name = 'Sorted Cash' },
            { model = 'bkr_prop_money_unsorted_01', name = 'Unsorted Cash' },
            { model = 'bkr_prop_money_wrapped_01',  name = 'Wrapped Cash' },
            { model = 'bkr_prop_moneypack_01a',     name = 'Money Pack 01A' },
            { model = 'bkr_prop_moneypack_02a',     name = 'Money Pack 02A' },
            { model = 'bkr_prop_moneypack_03a',     name = 'Money Pack 03A' },
        }
    },
    {
        Label = 'Weed Lab',
        Items = {
            { model = 'bkr_prop_fertiliser_pallet_01a',   name = 'Fertiliser Pallet 01A' },
            { model = 'bkr_prop_fertiliser_pallet_01b',   name = 'Fertiliser Pallet 01B' },
            { model = 'bkr_prop_fertiliser_pallet_01c',   name = 'Fertiliser Pallet 01C' },
            { model = 'bkr_prop_fertiliser_pallet_01d',   name = 'Fertiliser Pallet 01D' },
            { model = 'bkr_prop_fertiliser_pallet_02a',   name = 'Fertiliser Pallet 02A' },
            { model = 'bkr_prop_grow_lamp_02a',           name = 'Grow Lamp 02A' },
            { model = 'bkr_prop_grow_lamp_02b',           name = 'Grow Lamp 02B' },
            { model = 'bkr_prop_weed_01_small_01a',       name = 'Small Plant 01A' },
            { model = 'bkr_prop_weed_01_small_01b',       name = 'Small Plant 01B' },
            { model = 'bkr_prop_weed_01_small_01c',       name = 'Small Plant 01C' },
            { model = 'bkr_prop_weed_bag_01a',            name = 'Bag of Weed' },
            { model = 'bkr_prop_weed_bag_pile_01a',       name = 'Bag Pile' },
            { model = 'bkr_prop_weed_bigbag_01a',         name = 'Big Bag 01A' },
            { model = 'bkr_prop_weed_bigbag_02a',         name = 'Big Bag 02A' },
            { model = 'bkr_prop_weed_bigbag_03a',         name = 'Big Bag 03A' },
            { model = 'bkr_prop_weed_bigbag_open_01a',    name = 'Open Big Bag' },
            { model = 'bkr_prop_weed_bucket_01a',         name = 'Bucket 01A' },
            { model = 'bkr_prop_weed_bucket_01b',         name = 'Bucket 01B' },
            { model = 'bkr_prop_weed_bucket_01c',         name = 'Bucket 01C' },
            { model = 'bkr_prop_weed_bucket_01d',         name = 'Bucket 01D' },
            { model = 'bkr_prop_weed_bucket_open_01a',    name = 'Open Bucket' },
            { model = 'bkr_prop_weed_bud_01a',            name = 'Bud 01A' },
            { model = 'bkr_prop_weed_bud_01b',            name = 'Bud 01B' },
            { model = 'bkr_prop_weed_bud_02a',            name = 'Bud 02A' },
            { model = 'bkr_prop_weed_bud_02b',            name = 'Bud 02B' },
            { model = 'bkr_prop_weed_bud_pruned_01a',     name = 'Pruned Buds' },
            { model = 'bkr_prop_weed_chair_01a',          name = 'Growing Chair' },
            { model = 'bkr_prop_weed_dry_01a',            name = 'Drying Rack 01A' },
            { model = 'bkr_prop_weed_dry_02a',            name = 'Drying Rack 02A' },
            { model = 'bkr_prop_weed_dry_02b',            name = 'Drying Rack 02B' },
            { model = 'bkr_prop_weed_drying_01a',         name = 'Drying Tray 01A' },
            { model = 'bkr_prop_weed_drying_02a',         name = 'Drying Tray 02A' },
            { model = 'bkr_prop_weed_fan_ceiling_01a',    name = 'Ceiling Fan' },
            { model = 'bkr_prop_weed_fan_floor_01a',      name = 'Floor Fan' },
            { model = 'bkr_prop_weed_leaf_01a',           name = 'Leaf Pile' },
            { model = 'bkr_prop_weed_leaf_dry_01a',       name = 'Dry Leaf' },
            { model = 'bkr_prop_weed_lrg_01a',            name = 'Large Plant 01A' },
            { model = 'bkr_prop_weed_lrg_01b',            name = 'Large Plant 01B' },
            { model = 'bkr_prop_weed_med_01a',            name = 'Medium Plant 01A' },
            { model = 'bkr_prop_weed_med_01b',            name = 'Medium Plant 01B' },
            { model = 'bkr_prop_weed_pallet',             name = 'Weed Pallet' },
            { model = 'bkr_prop_weed_plantpot_stack_01a', name = 'Plantpot Stack 01A' },
            { model = 'bkr_prop_weed_plantpot_stack_01b', name = 'Plantpot Stack 01B' },
            { model = 'bkr_prop_weed_plantpot_stack_01c', name = 'Plantpot Stack 01C' },
            { model = 'bkr_prop_weed_scales_01a',         name = 'Scales 01A' },
            { model = 'bkr_prop_weed_scales_01b',         name = 'Scales 01B' },
            { model = 'bkr_prop_weed_smallbag_01a',       name = 'Small Bag 01A' },
            { model = 'bkr_prop_weed_spray_01a',          name = 'Spray Bottle' },
            { model = 'bkr_prop_weed_table_01a',          name = 'Weed Table 01A' },
            { model = 'bkr_prop_weed_table_01b',          name = 'Weed Table 01B' },
            { model = 'xm3_prop_xm3_spr_system_01a',      name = 'Spray System' },
            { model = 'xm3_prop_xm3_tank_water_01a',      name = 'Water Tank' },
            { model = 'xm3_prop_xm3_weed_set_01a',        name = 'Weed Set 01A' },
            { model = 'xm3_prop_xm3_weed_set_01b',        name = 'Weed Set 01B' },
            { model = 'xm3_prop_xm3_weed_set_02a',        name = 'Weed Set 02A' },
            { model = 'xm3_prop_xm3_weed_set_02b',        name = 'Weed Set 02B' },
        }
    },
    {
        Label = 'Coke Lab',
        Items = {
            { model = 'bkr_prop_coke_bakingsoda',          name = 'Baking Soda' },
            { model = 'bkr_prop_coke_bakingsoda_o',        name = 'Baking Soda (Opened)' },
            { model = 'bkr_prop_coke_block_01a',           name = 'Coke Block' },
            { model = 'bkr_prop_coke_bottle_01a',          name = 'Coke Bottle A' },
            { model = 'bkr_prop_coke_bottle_02a',          name = 'Coke Bottle B' },
            { model = 'bkr_prop_coke_box_01a',             name = 'Coke Box' },
            { model = 'bkr_prop_coke_boxeddoll',           name = 'Boxed Doll' },
            { model = 'bkr_prop_coke_cracktray_01',        name = 'Crack Tray' },
            { model = 'bkr_prop_coke_cut_01',              name = 'Cutting Board 01' },
            { model = 'bkr_prop_coke_cut_02',              name = 'Cutting Board 02' },
            { model = 'bkr_prop_coke_cutblock_01',         name = 'Cut Block' },
            { model = 'bkr_prop_coke_dehydrator_01',       name = 'Dehydrator' },
            { model = 'bkr_prop_coke_doll',                name = 'Coke Doll' },
            { model = 'bkr_prop_coke_doll_bigbox',         name = 'Doll Big Box' },
            { model = 'bkr_prop_coke_dollbox',             name = 'Doll Box' },
            { model = 'bkr_prop_coke_dollboxfolded',       name = 'Folded Doll Box' },
            { model = 'bkr_prop_coke_dollcast',            name = 'Doll Cast' },
            { model = 'bkr_prop_coke_dollmould',           name = 'Doll Mould' },
            { model = 'bkr_prop_coke_fullmetalbowl_02',    name = 'Full Metal Bowl' },
            { model = 'bkr_prop_coke_fullscoop_01a',       name = 'Full Scoop' },
            { model = 'bkr_prop_coke_fullsieve_01a',       name = 'Full Sieve' },
            { model = 'bkr_prop_coke_heat_01',             name = 'Heating Unit' },
            { model = 'bkr_prop_coke_heatbasket_01',       name = 'Heat Basket' },
            { model = 'bkr_prop_coke_metalbowl_01',        name = 'Metal Bowl 01' },
            { model = 'bkr_prop_coke_metalbowl_02',        name = 'Metal Bowl 02' },
            { model = 'bkr_prop_coke_metalbowl_03',        name = 'Metal Bowl 03' },
            { model = 'bkr_prop_coke_mixer_01',            name = 'Mixer' },
            { model = 'bkr_prop_coke_mixtube_01',          name = 'Mix Tube 01' },
            { model = 'bkr_prop_coke_mixtube_02',          name = 'Mix Tube 02' },
            { model = 'bkr_prop_coke_mixtube_03',          name = 'Mix Tube 03' },
            { model = 'bkr_prop_coke_mold_01a',            name = 'Mold 01' },
            { model = 'bkr_prop_coke_mold_02a',            name = 'Mold 02' },
            { model = 'bkr_prop_coke_mortalpestle',        name = 'Mortar & Pestle' },
            { model = 'bkr_prop_coke_painkiller_01a',      name = 'Painkiller Pack' },
            { model = 'bkr_prop_coke_pallet_01a',          name = 'Coke Pallet' },
            { model = 'bkr_prop_coke_plasticbowl_01',      name = 'Plastic Bowl' },
            { model = 'bkr_prop_coke_powder_01',           name = 'Powder' },
            { model = 'bkr_prop_coke_powder_02',           name = 'Powder (Variant)' },
            { model = 'bkr_prop_coke_powderbottle_01',     name = 'Powder Bottle A' },
            { model = 'bkr_prop_coke_powderbottle_02',     name = 'Powder Bottle B' },
            { model = 'bkr_prop_coke_powderedmilk',        name = 'Powdered Milk' },
            { model = 'bkr_prop_coke_powderedmilk_o',      name = 'Powdered Milk (Opened)' },
            { model = 'bkr_prop_coke_press_01aa',          name = 'Press AA' },
            { model = 'bkr_prop_coke_press_01b',           name = 'Press 01B' },
            { model = 'bkr_prop_coke_press_01b_frag_',     name = 'Press 01B (Fragments)' },
            { model = 'bkr_prop_coke_scale_01',            name = 'Scale 01' },
            { model = 'bkr_prop_coke_scale_02',            name = 'Scale 02' },
            { model = 'bkr_prop_coke_scale_03',            name = 'Scale 03' },
            { model = 'bkr_prop_coke_spatula_01',          name = 'Spatula 01' },
            { model = 'bkr_prop_coke_spatula_02',          name = 'Spatula 02' },
            { model = 'bkr_prop_coke_spatula_03',          name = 'Spatula 03' },
            { model = 'bkr_prop_coke_spatula_04',          name = 'Spatula 04' },
            { model = 'bkr_prop_coke_spoon_01',            name = 'Spoon' },
            { model = 'bkr_prop_coke_striplamp_long_01a',  name = 'Strip Lamp Long' },
            { model = 'bkr_prop_coke_striplamp_short_01a', name = 'Strip Lamp Short' },
            { model = 'bkr_prop_coke_table01a',            name = 'Coke Table' },
            { model = 'bkr_prop_coke_tablepowder',         name = 'Table Powder' },
            { model = 'bkr_prop_coke_testtubes',           name = 'Test Tubes' },
            { model = 'bkr_prop_coke_tin_01',              name = 'Tin Can' },
            { model = 'bkr_prop_coke_tub_01a',             name = 'Tub 01A' },
            { model = 'bkr_prop_coke_tube_01',             name = 'Tube 01' },
            { model = 'bkr_prop_coke_tube_02',             name = 'Tube 02' },
            { model = 'bkr_prop_coke_tube_03',             name = 'Tube 03' },
        }
    },
    {
        Label = 'Meth Lab',
        Items = {
            { model = 'bkr_prop_biker_tool_broom',          name = 'Broom' },
            { model = 'bkr_prop_meth_acetone',              name = 'Acetone' },
            { model = 'bkr_prop_meth_ammonia',              name = 'Ammonia' },
            { model = 'bkr_prop_meth_bigbag_01a',           name = 'Meth Big Bag 01A' },
            { model = 'bkr_prop_meth_bigbag_02a',           name = 'Meth Big Bag 02A' },
            { model = 'bkr_prop_meth_bigbag_03a',           name = 'Meth Big Bag 03A' },
            { model = 'bkr_prop_meth_bigbag_04a',           name = 'Meth Big Bag 04A' },
            { model = 'bkr_prop_meth_chiller_01a',          name = 'Chiller Unit' },
            { model = 'bkr_prop_meth_hcacid',               name = 'Hydrochloric Acid' },
            { model = 'bkr_prop_meth_lithium',              name = 'Lithium' },
            { model = 'bkr_prop_meth_openbag_01a',          name = 'Open Bag 01A' },
            { model = 'bkr_prop_meth_openbag_01a_frag_',    name = 'Open Bag 01A (Fragments)' },
            { model = 'bkr_prop_meth_openbag_02',           name = 'Open Bag 02' },
            { model = 'bkr_prop_meth_pallet_01a',           name = 'Meth Pallet' },
            { model = 'bkr_prop_meth_phosphorus',           name = 'Phosphorus' },
            { model = 'bkr_prop_meth_pseudoephedrine',      name = 'Pseudoephedrine' },
            { model = 'bkr_prop_meth_sacid',                name = 'Sulfuric Acid' },
            { model = 'bkr_prop_meth_scoop_01a',            name = 'Meth Scoop' },
            { model = 'bkr_prop_meth_smallbag_01a',         name = 'Meth Small Bag' },
            { model = 'bkr_prop_meth_smashedtray_01',       name = 'Smashed Tray 01' },
            { model = 'bkr_prop_meth_smashedtray_01_frag_', name = 'Smashed Tray 01 (Fragments)' },
            { model = 'bkr_prop_meth_smashedtray_02',       name = 'Smashed Tray 02' },
            { model = 'bkr_prop_meth_sodium',               name = 'Sodium' },
            { model = 'bkr_prop_meth_table01a',             name = 'Meth Table' },
            { model = 'bkr_prop_meth_toulene',              name = 'Toluene' },
            { model = 'bkr_prop_meth_tray_01a',             name = 'Meth Tray 01A' },
            { model = 'bkr_prop_meth_tray_01b',             name = 'Meth Tray 01B' },
            { model = 'bkr_prop_meth_tray_02a',             name = 'Meth Tray 02A' },
        }
    },
    {
        Label = 'LSD Lab',
        Items = {
            { model = 'xm3_prop_xm3_bag_small_01a',       name = 'Bag Small' },
            { model = 'xm3_prop_xm3_drying_tabs_b1',      name = 'Drying Tabs B1' },
            { model = 'xm3_prop_xm3_drying_tabs_b3',      name = 'Drying Tabs B3' },
            { model = 'xm3_prop_xm3_drying_tabs_f1',      name = 'Drying Tabs F1' },
            { model = 'xm3_prop_xm3_drying_tabs_f2',      name = 'Drying Tabs F2' },
            { model = 'xm3_prop_xm3_drying_tabs_f3',      name = 'Drying Tabs F3' },
            { model = 'xm3_prop_xm3_lab_acetone',         name = 'Lab Acetone' },
            { model = 'xm3_prop_xm3_lab_ammonia',         name = 'Lab Ammonia' },
            { model = 'xm3_prop_xm3_lab_hcacid',          name = 'Lab HCl Acid' },
            { model = 'xm3_prop_xm3_lab_phosphorus',      name = 'Lab Phosphorus' },
            { model = 'xm3_prop_xm3_lab_toulene',         name = 'Lab Toulene' },
            { model = 'xm3_prop_xm3_lab_tray_01b',        name = 'Lab Tray' },
            { model = 'xm3_prop_xm3_lsd_beaker_01a',      name = 'Beaker 01A' },
            { model = 'xm3_prop_xm3_lsd_beaker_01b',      name = 'Beaker 01B' },
            { model = 'xm3_prop_xm3_lsd_beaker_02a',      name = 'Beaker 02A' },
            { model = 'xm3_prop_xm3_lsd_bottle_01a',      name = 'Bottle 01A' },
            { model = 'xm3_prop_xm3_lsd_bottle_02b',      name = 'Bottle 02B' },
            { model = 'xm3_prop_xm3_lsd_plate_01a',       name = 'Plate' },
            { model = 'xm3_prop_xm3_lsd_tray_03a',        name = 'Tray 03A' },
            { model = 'xm3_prop_xm3_pipette_01a',         name = 'Pipette 01A' },
            { model = 'xm3_prop_xm3_pipette_01b_test01',  name = 'Pipette Test01' },
            { model = 'xm3_prop_xm3_pipette_01b_test02',  name = 'Pipette Test02' },
            { model = 'xm3_prop_xm3_product_bottle_01',   name = 'Product Bottle' },
            { model = 'xm3_prop_xm3_product_box_01',      name = 'Product Box' },
            { model = 'xm3_prop_xm3_product_tabs_full',   name = 'Tabs Full' },
            { model = 'xm3_prop_xm3_product_tabs_single', name = 'Tabs Single' },
            { model = 'xm3_prop_xm3_rack_val_01b',        name = 'Rack Valve 01B' },
            { model = 'xm3_prop_xm3_rack_val_01a',        name = 'Rack Valve 01A' },
            { model = 'xm3_prop_xm3_shelves_01a',         name = 'Shelves' },
            { model = 'xm3_prop_xm3_tent_01a',            name = 'Tent' },
            { model = 'xm3_prop_xm3_lsd_appar_01a',       name = 'Apparatus 01A' },
            { model = 'xm3_prop_xm3_lsd_appar_02a',       name = 'Apparatus 02A' },
            { model = 'xm3_prop_xm3_lsd_bottles1',        name = 'Bottles Set 1' },
            { model = 'xm3_prop_xm3_lsd_bottles2',        name = 'Bottles Set 2' },
            { model = 'xm3_prop_xm3_lsd_bottle_03a',      name = 'Bottle 03A' },
            { model = 'xm3_prop_xm3_lsd_flask',           name = 'Flask' },
            { model = 'xm3_prop_xm3_lsd_tray_02a',        name = 'Tray 02A' },
            { model = 'xm3_prop_xm3_set_eqpt_lsd',        name = 'Equipment Set' },
        }
    },
    {
        Label = 'Lab Equipment',
        Items = {
            { model = 'v_med_lab_fridge',                   name = 'Lab Fridge' },
            { model = 'xm3_prop_xm3_lab_ammonia',           name = 'Ammonia' },
            { model = 'xm3_prop_xm3_lab_toulene',           name = 'Toulene' },
            { model = 'xm3_prop_xm3_lab_hcacid',            name = 'Hydrochloric Acid' },
            { model = 'xm3_prop_xm3_chem_vial_02b_s',       name = 'Chem Vial 02B S' },
            { model = 'xm3_prop_xm3_cs_vial_01a',           name = 'CS Vial 01A' },
            { model = 'xm3_prop_xm3_med_xray_01a',          name = 'Med X‑Ray 01A' },
            { model = 'xm3_prop_xm3_med_chm_01a',           name = 'Med Chem 01A' },
            { model = 'xm3_prop_xm3_med_bin_01a',           name = 'Med Bin 01A' },
            { model = 'xm3_prop_xm3_med_glvbox_01a',        name = 'Med Glove Box 01A' },
            { model = 'xm3_prop_xm3_med_glvbox_01b',        name = 'Med Glove Box 01B' },
            { model = 'xm3_prop_xm3_med_set_01c',           name = 'Med Set 01C' },
            { model = 'xm3_prop_xm3_med_set_02a',           name = 'Med Set 02A' },
            { model = 'xm3_prop_xm3_med_set_02b',           name = 'Med Set 02B' },
            { model = 'xm3_prop_xm3_med_wastebin_01a',      name = 'Med Wastebin 01A' },
            { model = 'xm3_prop_xm3_med_trolley_02a',       name = 'Med Trolley 02A' },
            { model = 'xm3_prop_xm3_med_trolley_01a',       name = 'Med Trolley 01A' },
            { model = 'xm3_prop_xm3_set_eqpt_lsd',          name = 'Equipment Set LSD' },
        },
    },
    {
        Label = 'Storage & Misc',
        Items = {
            { model = 'prop_cabinet_02b',          name = 'Storage Cabinet' },
            { model = 'prop_fridge_01',            name = 'Fridge' },
            { model = 'prop_toolchest_05',         name = 'Tool Chest' },
            { model = 'bkr_prop_fakeid_binbag_01', name = 'Trash Bag' },
            { model = 'bkr_prop_fakeid_table',     name = 'Fake ID Table' },
        },
    },
}
